import { theme } from "@/src/constants/themes";
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  keyboardAvoid: {
    flex: 1,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    padding: 20,
    paddingBottom: 40,
  },
  header: {
    marginBottom: 24,
  },
  headerTitle: {
    fontSize: 28,
    fontWeight: "700",
    color: theme.colors.text || "#1F2937",
    marginBottom: 4,
  },
  headerSubtitle: {
    fontSize: 14,
    color: theme.colors.textLight || "#6B7280",
    lineHeight: 20,
  },
  balanceCard: {
    backgroundColor: "#EF4444",
    borderRadius: 16,
    padding: 20,
    marginBottom: 24,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
  },
  balanceLabel: {
    fontSize: 14,
    color: "rgba(255, 255, 255, 0.8)",
    marginBottom: 4,
    fontWeight: "500",
  },
  balanceAmount: {
    fontSize: 36,
    fontWeight: "700",
    color: "#FFFFFF",
  },
  inputSection: {
    marginBottom: 20,
  },
  inputLabel: {
    fontSize: 14,
    fontWeight: "600",
    color: theme.colors.text || "#374151",
    marginBottom: 8,
  },
  amountContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderRadius: 12,
    borderWidth: 2,
    borderColor: "#E5E7EB",
    paddingHorizontal: 16,
    height: 56,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  currencySymbol: {
    fontSize: 16,
    fontWeight: "600",
    color: "#6B7280",
    marginRight: 8,
  },
  amountInput: {
    flex: 1,
    fontSize: 24,
    fontWeight: "600",
    color: theme.colors.text || "#111827",
    padding: 0,
  },
  errorText: {
    fontSize: 12,
    color: "#EF4444",
    marginTop: 4,
    fontWeight: "500",
  },
  quickAmountSection: {
    marginBottom: 24,
  },
  quickAmountLabel: {
    fontSize: 14,
    fontWeight: "600",
    color: theme.colors.text || "#374151",
    marginBottom: 12,
  },
  quickAmountButtons: {
    flexDirection: "row",
    gap: 10,
  },
  quickAmountButton: {
    flex: 1,
    backgroundColor: "#FFFFFF",
    borderRadius: 10,
    paddingVertical: 14,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: "#E5E7EB",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  quickAmountButtonActive: {
    backgroundColor: "#EF4444",
    borderColor: "#DC2626",
  },
  quickAmountButtonDisabled: {
    opacity: 0.4,
  },
  quickAmountButtonText: {
    fontSize: 14,
    fontWeight: "600",
    color: theme.colors.text || "#374151",
  },
  quickAmountButtonTextActive: {
    color: "#FFFFFF",
  },
  quickAmountButtonTextDisabled: {
    color: "#9CA3AF",
  },
  sectionHeader: {
    marginBottom: 16,
    marginTop: 8,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: theme.colors.text || "#1F2937",
  },
  textInput: {
    backgroundColor: "#FFFFFF",
    borderRadius: 12,
    borderWidth: 2,
    borderColor: "#E5E7EB",
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontSize: 16,
    color: theme.colors.text || "#111827",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  notesInput: {
    height: 100,
    textAlignVertical: "top",
    paddingTop: 14,
  },
  withdrawalButton: {
    backgroundColor: "#EF4444",
    borderRadius: 12,
    paddingVertical: 16,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 8,
    marginBottom: 16,
    shadowColor: "#EF4444",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  withdrawalButtonDisabled: {
    backgroundColor: "#9CA3AF",
    shadowColor: "#000",
    shadowOpacity: 0.1,
  },
  withdrawalButtonText: {
    fontSize: 16,
    fontWeight: "700",
    color: "#FFFFFF",
  },
  infoNotice: {
    backgroundColor: "#FEF3C7",
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: "#FCD34D",
  },
  infoTitle: {
    fontSize: 14,
    fontWeight: "600",
    color: "#78350F",
    marginBottom: 4,
  },
  infoText: {
    fontSize: 13,
    color: "#92400E",
    lineHeight: 18,
  },
  securityNotice: {
    backgroundColor: "#F3F4F6",
    borderRadius: 12,
    padding: 16,
    alignItems: "center",
  },
  securityText: {
    fontSize: 13,
    color: "#6B7280",
    textAlign: "center",
  },
});
